### ISSUE TITLE
Aligning New components generated

### ISSUE THREAD

**Issue by snayak46** [mainawycliffe/angular-dynamic-form-fields-in-reactive-forms#1]
First of all, thanks for great explaination

I want to align the form group that was generated vertically rather horizontally.
Currently the elements that gets generated are displayed to right side and then bottom. 

Request you to assist with this

**Comment by mainawycliffe** [comment]
Hi, you can achieve this by adjusting the size of the bootstrap grid system, at this [point ](https://github.com/mainawycliffe/angular-dynamic-form-fields-in-reactive-forms/blob/c0d40bfbc8505c176f61b9e0328c9f91d4040829/src/app/app.component.html#L24) from:

```html
<div class="col-6" *ngFor="let contact of contactFormGroup.controls; let i = index;">
...
</div
```

to

```html
<div class="col-12" *ngFor="let contact of contactFormGroup.controls; let i = index;">
...
</div>
```

I am using the bootstrap grid system, which you can learn more about [here](https://getbootstrap.com/docs/4.2/layout/grid/)
